# Generated by Django 3.2.3 on 2023-09-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='nell', upload_to='photo_recipe/'),
            preserve_default=False,
        ),
    ]
