# Generated by Django 3.2.3 on 2023-09-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0002_recipe_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='picture',
            new_name='image',
        ),
    ]
