version: '3.3'

volumes:
  pg_data_foodgram:
  media_foodgram:
  static_foodgram:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    image: etl0n/foodgram_backend
    env_file: .env
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/media
      - ../data:/data
  frontend:
    image: etl0n/foodgram_frontend
    volumes:
      - static_foodgram:/static
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - 7000:80
    volumes:
      - media_foodgram:/media
      - static_foodgram:/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

